source activate ~/anaconda/envs/rsimcon-pyassimp-minimal/
python3 regression.py
python3 test_boolean.py
python3 test_bounds.py
python3 test_convex.py
python3 test_creation.py
python3 test_dxf.py
python3 test_export.py
python3 test_graph.py
python3 test_grouping.py
python3 test_identifier.py
python3 test_inertia.py
python3 test_integrate.py
python3 test_mesh.py
python3 test_normals.py
python3 test_nsphere.py
python3 test_packing.py
python3 test_paths.py
python3 test_permutate.py
python3 test_points.py
python3 test_primitives.py
python3 test_proximity.py
python3 test_ray.py
python3 test_scene.py
python3 test_section.py
python3 test_simplify.py
python3 test_triangles.py
python3 test_units.py
python3 test_utility.py
python3 test_visual.py
python3 test_voxel.py
